[package]
name = "uuid-rs"
description = "A Universally Unique IDentifier (UUID)"
authors = ["Awh6al <awh6al@yandex.com>"]
documentation = "https://docs.rs/uuid-rs"
version = "0.3.6"
license = "MIT"
edition = "2018"
readme = "README.md"
categories = [
    "data-structures",
    "algorithms",
    "cryptography"
]
keywords = [
    "uuid",
    "unique",
    "global",
    "rand",
]
repository = "https://github.com/awh6al/uuid-rs"

[dependencies]
regex = "1.3.9"
rand = "0.7.3"
mac_address = "1.0.3"
md5 = "0.7.0"
sha1 = "0.6.0"

[package.metadata.docs.rs]