[package]
name = "uuid-rs"
authors = ["Awh6al <awh6al@yandex.com>"]
documentation = "https://docs.rs/uuid-rs"
version = "0.2.4"
license = "MIT"
edition = "2018"
readme = "README.md"
categories = [
    "data-structures",
    "algorithms",
    "cryptography"
]
keywords = [
    "uuid",
    "unique",
    "global",
    "rand",
]
description = "A Universally Unique IDentifier (UUID)"
repository = "https://github.com/awh6al/uuid-rs"

[dependencies]
regex = "1.3.9"
rand = "0.7.3"

[dependencies.mac_address]
optional = true
version = "1.0.3"

[dependencies.md5]
optional = true
version = "0.7.0"

[dependencies.sha1]
optional = true
version = "0.6.0"

[features]
mac = ["mac_address"]
hash = ["md5", "sha1"]

[package.metadata.docs.rs]