[package]
name = "uuid-rs"
description = "A Universally Unique IDentifier (UUID)"
authors = ["Awh6al <awh6al@yandex.com>"]
documentation = "https://docs.rs/uuid-rs"
version = "0.3.2"
license = "MIT"
edition = "2018"
readme = "README.md"
categories = [
    "data-structures",
    "algorithms",
    "cryptography"
]
keywords = [
    "uuid",
    "unique",
    "global",
    "rand",
]
repository = "https://github.com/awh6al/uuid-rs"

[dependencies]
regex = "1.3.9"
rand = { version = "0.7.3", optional = true }
mac_address = { version = "1.0.3", optional = true }
md5 = { version = "0.7.0", optional = true }
sha1 = { version = "0.6.0", optional = true }

[features]
mac = ["mac_address"]
hash = ["md5", "sha1"]

[package.metadata.docs.rs]