[package]
name = "uuid-rs"
authors = ["Awh6al <awh6al@yandex.com>"]
version = "0.1.3"
license = "MIT"
edition = "2018"
readme = "README.md"
categories = [
    "data-structures",
]
keywords = [
    "uuid",
    "unique",
]
description = "A Universally Unique IDentifier (UUID)"
repository = "https://github.com/awh6al/uuid-rs"
documentation = "https://docs.rs/uuid-rs"

[dependencies]
mac_address = "1.0.3"
regex = "1.3.7"
rand = "0.7"
md5 = "0.7.0"
sha1 = "0.6.0"

[package.metadata.docs.rs]