[package]
name = "uuid-rs"
authors = ["Awh6al <awh6al@yandex.com>"]
documentation = "https://docs.rs/uuid-rs"
version = "0.2.0"
license = "MIT"
edition = "2018"
readme = "README.md"
categories = [
    "data-structures",
]
keywords = [
    "uuid",
    "unique",
]
description = "A Universally Unique IDentifier (UUID)"
repository = "https://github.com/awh6al/uuid-rs"

[dependencies]
regex = "1.3.7"
rand = "0.7.3"

[dependencies.mac_address]
optional = true
version = "1.0.3"

[dependencies.md5]
optional = true
version = "0.7.0"

[dependencies.sha1]
optional = true
version = "0.6.0"

[features]
v1 = ["mac_address"]
v3 = ["md5"]
v5 = ["sha1"]

[package.metadata.docs.rs]