[package]
name = "uuid-rs"
description = "A Simple Universally Unique IDentifier (UUID)"
authors = ["Awh6al <awh6al@yandex.com>"]
documentation = "https://docs.rs/uuid-rs"
version = "0.6.1"
license = "MIT"
edition = "2018"
readme = "README.md"
categories = [
    "data-structures",
    "algorithms",
    "cryptography"
]
keywords = [
    "uuid",
    "unique",
    "global",
    "rand",
]
repository = "https://github.com/awh6al/uuid-rs"

[dependencies]
mac_address = { version = "1.0.3", optional = true }
rand = { version = "0.7.3", optional = true }
md5 = { version = "0.7.0", optional = true }
sha1 = { version = "0.6.0", optional = true }

[dev-dependencies.regex]
version = "1.3.9"

[features]
mac = ["mac_address", "rand"]
random = ["rand"]
hash_sha1 = ["sha1"]
hash_md5 = ["md5"]

[package.metadata.docs.rs]
all-features = true

